export const afghanCities = [
  { text: 'بدخشان', value: 'BDN' },
  { text: 'کونر', value: 'KNR' },
  { text: 'بادغیس', value: 'BDG' },
  { text: 'کندوز', value: 'KDZ' },
  { text: 'بغلان', value: 'BAG' },
  { text: 'لغمان', value: 'LGM' },
  { text: 'بلخ', value: 'BLH' },
  { text: 'لوگر', value: 'LGR' },
  { text: 'بامیان', value: 'BAM' },
  { text: 'ننگرهار', value: 'NGR' },
  { text: 'دایکندی', value: 'DYK' },
  { text: 'نیمروز', value: 'NRZ' },
  { text: 'فراه', value: 'FRH' },
  { text: 'نورستان', value: 'NUR' },
  { text: 'فریاب', value: 'FYB' },
  { text: 'پکتیا', value: 'PAK' },
  { text: 'غزنی', value: 'GAZ' },
  { text: 'پکتیکا', value: 'PKT' },
  { text: 'غور', value: 'GHR' },
  { text: 'پنجیشیر', value: 'PJR' },
  { text: 'هملند', value: 'HEL' },
  { text: 'پروان', value: 'PRN' },
  { text: 'هرات', value: 'HRT' },
  { text: 'سمنگان', value: 'SAM' },
  { text: 'جوزجان', value: 'JZJ' },
  { text: 'سرپل', value: 'SRP' },
  { text: 'کابل', value: 'KBL' },
  { text: 'تخار', value: 'TAK' },
  { text: 'کندهار', value: 'KDR' },
  { text: 'اروزگان', value: 'ORZ' },
  { text: 'کپیسا', value: 'KPS' },
  { text: 'وردک', value: 'WDK' },
  { text: 'خوست', value: 'KST' },
  { text: 'زابل', value: 'ZBL' },
]

export const iranPlateLetters = [
  { text: 'ع', value: 'ein' },
  { text: 'ط', value: 'ta' },
  { text: 'ن', value: 'n' },
  { text: 'الف', value: 'alef' },
  { text: 'و', value: 'v' },
  { text: 'ص', value: 'sad' },
  { text: 'ق', value: 'q' },
  { text: 'ل', value: 'l' },
  { text: 'س', value: 's' },
  { text: 'ی', value: 'y' },
  { text: 'ه', value: 'h' },
  { text: 'د', value: 'd' },
  { text: 'م', value: 'm' },
  { text: 'ب', value: 'b' },
]
